Add files to generate QC report
Boehringer-Ingelheim/dv.filter pull request #3
Opened 2024-06-26 12:36 UTC by mingstat

2024-06-27 10:12 UTC, sorinvoicu requested changes

2024-06-27 10:12 UTC, sorinvoicu commented on tests/testthat/test-categorical-filter-missing.R
> +test_that("For a chosen categorical filter with missing values, an item signifying missingness is incorporated at the top of the filter dropdown menu. By default, all missing values are included." %>
use # nolint here, same for all others

2024-06-27 10:12 UTC, sorinvoicu commented on tests/testthat/test-categorical-filter-missing.R
> +            vdoc[["add_spec"]](specs$filter_categorical_missing), { # nolint
nolint can be removed

2024-06-28 07:06 UTC, closed without merging

2024-06-28 07:07 UTC, mingstat commented
A new PR has been created to merge commits into rc from dev branch.